//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
        }
    
        public int codProducto { get; set; }
        public string sku { get; set; }
        public string nombre { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precioCosto { get; set; }
        public Nullable<decimal> precioVenta { get; set; }
        public Nullable<int> idBodega { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> cantDaniados { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        public virtual EstadoProducto EstadoProducto { get; set; }
    }
}
